
# <center><font>  Numpy Crash Course</font><center>


In [ ]:
import numpy as np

**Creating Array of Zeros**

In [ ]:
a = np.zeros((2, 2))   # Create an array of all zeros of specified shape
print(a) 

[[0. 0.]
 [0. 0.]]


**Creating Array of Ones**

In [ ]:
a = np.ones((2, 2))    # Create an array of all ones
print(a)

[[1. 1.]
 [1. 1.]]


**Creating an Array of Constant Values** <br>
Here we chose the constant value to be `7`

In [ ]:
b = np.full((2, 2), 7)  # Create a constant array
print(b)   

[[7 7]
 [7 7]]


**Creating an Identity Matrix**

In [ ]:
c = np.eye(2)   # Create a 2 x 2 identity matrix
print(c)  

[[1. 0.]
 [0. 1.]]


**Creating an Array of Random Values**

In [ ]:
d = np.random.randint(5,10, size=(2, 2))  # Create a 2x2 array filled with random values from 5-10
print(d)

[[7 7]
 [6 8]]


###  <font style="color:rgb(134,19,348)"> Reshaping an Array  </font> 

In [ ]:
nums = np.arange(16)
print(nums)
print(nums.shape)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15]
(16,)


**Now lets reshape that 16, to a 4x4 array**

In [ ]:
nums = nums.reshape((4, 4))
print('Reshaped:\n', nums)
print(nums.shape)

Reshaped:
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]
(4, 4)


**Using -1** 

The -1 in reshape corresponds to an unknown dimension that numpy will figure out based on all other dimensions and the array size. We Can only specify one unknown dimension. For example, sometimes we might have an unknown number of data points, and so we can use -1 instead without worrying about the true number.

In [ ]:
nums = nums.reshape((4,-1 ))
print('Reshaped with -1:\n', nums)
print(nums.shape)

Reshaped with -1:
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]
(4, 4)


**NumPy supports an object-oriented paradigm, such that ndarray has a number of methods and attributes, with functions similar to ones in the outermost NumPy namespace.** <br>
For example, we can do both: 

In [ ]:
nums = np.arange(8)
print(nums.min())     
print(np.min(nums))   

0
0


##  <font style="color:rgb(134,19,348)"> Flatten vs Ravel   </font> 

 The primary functional difference is that flatten() is a method of an ndarray object and hence can only be called for true numpy arrays. In contrast ravel() is a library-level function and hence can be called on any object that can successfully be parsed. For example ravel() will work on a list of ndarrays, while flatten (obviously) won't

In [ ]:
print (b)

[[7 7]
 [7 7]]


In [ ]:
b.flatten() 

array([7, 7, 7, 7])

In [ ]:
# flattening the array ...used in computer vision a lot..
b.ravel()

array([7, 7, 7, 7])

## Array Operations/Math  

NumPy supports many elementwise operations:

In [ ]:
x = np.array([[1, 2],
              [3, 4]], dtype=np.float64)
y = np.array([[5, 6],
              [7, 8]], dtype=np.float64)

**Addition**

In [ ]:
print(x + y)
print(np.add(x, y))

[[ 6.  8.]
 [10. 12.]]
[[ 6.  8.]
 [10. 12.]]


**Subtraction**

In [ ]:
print(x - y)
print(np.subtract(x, y))

[[-4. -4.]
 [-4. -4.]]
[[-4. -4.]
 [-4. -4.]]


**Multiplication**

In [ ]:
print(x * y)
print(np.multiply(x, y))

[[ 5. 12.]
 [21. 32.]]
[[ 5. 12.]
 [21. 32.]]


**Division**

How do we elementwise divide between two arrays?

In [ ]:
print(x / y)
print(np.divide(x, y))

[[0.2        0.33333333]
 [0.42857143 0.5       ]]
[[0.2        0.33333333]
 [0.42857143 0.5       ]]


<small>**Note:** This is elementwise multiplication, not matrix multiplication. We instead use the dot function to compute inner products of vectors, to multiply a vector by a matrix, and to multiply matrices. dot is available both as a function in the numpy module and as an instance method of array objects </small>



 ##  Numpy Functions 
There are many useful functions built into NumPy, and often we're able to express them across specific axes of the ndarray:

In [ ]:
x = np.array([[1, 2, 3], 
              [4, 5, 6]])

print(np.sum(x))          # Compute sum of all elements
print(np.sum(x, axis=0))  # Compute sum of each row
print(np.sum(x, axis=1))  # Compute sum of each col

21
[5 7 9]
[ 6 15]


**Note:** `Axis 0` is `row` and `Axis 1` is `column`

**np.Max**

In [ ]:
print(np.max(x, axis=1))  # Compute max of each row

[3 6]


**Argmax** <br>
How can we compute the index of the max value of each row? Useful, to say, find the class that corresponds to the maximum score for an input image.

In [ ]:
x = np.array([[1, 7, 3], 
              [4, 5, 6]])

print(np.argmax(x, axis=0)) # Compute index of max of each row

[1 0 1]


**Computing on a specific Axis**

In [ ]:
x = np.array([[1,2],[3,4]])
print("array: ",x)
print("-----")
print ("sum of all elements : ",np.sum(x))  # Compute sum of all elements; prints "10"
print ("sum of rows : ", np.sum(x, axis=0))  # Compute sum of each rows; prints "[4 6]"
print ("sum of cols : " ,np.sum(x, axis=1))  # Compute sum of each cols; prints "[3 7]"

array:  [[1 2]
 [3 4]]
-----
sum of all elements :  10
sum of rows :  [4 6]
sum of cols :  [3 7]


**Slicing** <br>
Numpy slicing is pretty similar to python list slicing

In [ ]:
b[0:2,0]  # from row 0 and 1 take column 1st

array([7, 7])

In [ ]:
x[:,1:2]  # gives all rows of col 2

array([[2],
       [4]])

**Reversing an axis**

In [ ]:
a = np.array([[1, 2, 3, 4],
              [5, 6, 7, 8],
              [9, 10, 11, 12]])

# The following reverses the first row and prints it out
print('Reversing the first row (a[0, ::-1]) :\n', a[0, ::-1]) 

Reversing the first row (a[0, ::-1]) :
 [4 3 2 1]
